port: 4000
safe: true
pygments: false
lsi: true
excerpt_separator: <!--more--> 
category-list: [Java, Programming, Ideas, Jekyll, Security, Series]

company: Develop4 Technologies
name: Develop4 Technologies Ltd.
registration: 04598288
topbartitle: [ Develop4 Technologies ]