port: 4000
safe: true
highlighter: null
lsi: true
excerpt_separator: <!--summary-above--> 
#category-list: [Java, Programming, Ideas, Jekyll, Security, Series, Projects, Blogs, AMP, Security]

company: Develop4
name: Develop4 Ltd.
registration: 04598288
topbartitle: [ Develop4 ]